//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ProfileEntities : DbContext
    {
        public ProfileEntities()
            : base("name=ProfileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<Industry> Industries { get; set; }
        public DbSet<Education> Educations { get; set; }
        public DbSet<EduDegree> EduDegrees { get; set; }
        public DbSet<EduType> EduTypes { get; set; }
        public DbSet<EmployerType> EmployerTypes { get; set; }
        public DbSet<Employment> Employments { get; set; }
        public DbSet<BloodGroup> BloodGroups { get; set; }
        public DbSet<AdminLogin> AdminLogins { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserRegistration> UserRegistrations { get; set; }
        public DbSet<SubCaste> SubCastes { get; set; }
        public DbSet<MaritalStatu> MaritalStatus { get; set; }
        public DbSet<Complexion> Complexions { get; set; }
        public DbSet<Height> Heights { get; set; }
        public DbSet<Weight> Weights { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Taluka> Talukas { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<VisitorDeail> VisitorDeails { get; set; }
        public DbSet<OtherCasteUserRegistration> OtherCasteUserRegistrations { get; set; }
    
        public virtual ObjectResult<Get_Education_Result> Get_Education(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Education_Result>("Get_Education", userIDParameter);
        }
    
        public virtual ObjectResult<Get_Employment_Result> Get_Employment(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Employment_Result>("Get_Employment", userIDParameter);
        }
    
        public virtual ObjectResult<SPQuickSearch_Result> SPQuickSearch(string myAppID)
        {
            var myAppIDParameter = myAppID != null ?
                new ObjectParameter("MyAppID", myAppID) :
                new ObjectParameter("MyAppID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPQuickSearch_Result>("SPQuickSearch", myAppIDParameter);
        }
    
        public virtual ObjectResult<SPAdvancedSearch_Result> SPAdvancedSearch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPAdvancedSearch_Result>("SPAdvancedSearch");
        }
    
        public virtual ObjectResult<Get_Profile_Result> Get_Profile(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Profile_Result>("Get_Profile", userIDParameter);
        }
    }
}
