//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> WorkID { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> MritalStatus { get; set; }
        public string RAddress { get; set; }
        public string ImagePath { get; set; }
        public string MyAppID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> SubCasteID { get; set; }
        public Nullable<int> ComplexionID { get; set; }
        public Nullable<int> HeightID { get; set; }
        public Nullable<int> WeightID { get; set; }
        public Nullable<int> PhysicallyChalengeID { get; set; }
        public Nullable<int> SpectacleID { get; set; }
        public Nullable<int> TalukaID { get; set; }
        public string BirthPlace { get; set; }
        public string BirthName { get; set; }
        public string BirthTime { get; set; }
        public string Gotra { get; set; }
        public string EducationDetail { get; set; }
        public Nullable<int> CareerID { get; set; }
        public string ServiceDetail { get; set; }
        public string SalaryAnual { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherOccupation { get; set; }
        public string ContactNo { get; set; }
        public string MamaPlace { get; set; }
        public string MamaName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string MulGaon { get; set; }
    }
}
